package mvc.view;

import java.util.ArrayList;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class Screen extends JFrame {

    /**
     * Creates new form
     */
	ArrayList<JCheckBox> hobby = new ArrayList<JCheckBox>();
	
    public Screen() {
        initComponents();
        hobby.add(this.checkMovies);
        hobby.add(this.checkSport);
        hobby.add(this.checkReading);
        hobby.add(this.checkMusic);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGender = new ButtonGroup();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        txtName = new JTextField();
        txtAge = new JTextField();
        txtHeight = new JTextField();
        txtWeight = new JTextField();
        radioFemale = new JRadioButton();
        radioMale = new JRadioButton();
        jLabel5 = new JLabel();
        comboState = new JComboBox();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        checkMusic = new JCheckBox();
        checkMovies = new JCheckBox();
        checkReading = new JCheckBox();
        checkSport = new JCheckBox();
        jScrollPane1 = new JScrollPane();
        exitArea = new JTextArea();
        btnInput = new JButton();
        btnClear = new JButton();
        btnInsert = new JButton();
        btnAlter = new JButton();
        btnRemove = new JButton();
        btnList = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Example");
        setMaximumSize(new java.awt.Dimension(619, 432));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(619, 432));
        jPanel1.setMinimumSize(new java.awt.Dimension(619, 432));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Idade");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Altura");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Peso");

        txtName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtName.setNextFocusableComponent(txtAge);
        
        txtAge.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAge.setNextFocusableComponent(txtHeight);
        
        txtHeight.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHeight.setNextFocusableComponent(txtWeight);
        
        txtWeight.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnGender.add(radioFemale);
        radioFemale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radioFemale.setText("Female");

        btnGender.add(radioMale);
        radioMale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radioMale.setText("Male");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Gender");

        comboState.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboState.setModel(new javax.swing.DefaultComboBoxModel(new String[]
        		{ "Choose...", "Acre - AC", "Alagoas - AL", "Amapá - AP", "Amazonas - AM", 
        		"Bahia  - BA", "Ceará - CE", "Distrito Federal  - DF", "Espírito Santo - ES",
        		"Goiás - GO", "Maranhão - MA", "Mato Grosso - MT", "Mato Grosso do Sul - MS",
        		"Minas Gerais - MG", "Pará - PA", "Paraíba - PB", "Paraná - PR", "Pernambuco - PE",
        		"Piauí - PI", "Rio de Janeiro - RJ", "Rio Grande do Norte - RN", "Rio Grande do Sul - RS",
        		"Rondônia - RO", "Roraima - RR", "Santa Catarina - SC", "São Paulo - SP", "Sergipe - SE", "Tocantins - TO" }));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("From:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Likes:");

        checkMusic.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkMusic.setText("Music");

        checkMovies.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkMovies.setText("Movies");

        checkReading.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkReading.setText("Reading");

        checkSport.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkSport.setText("Sports");

        exitArea.setColumns(20);
        exitArea.setRows(5);
        jScrollPane1.setViewportView(exitArea);

        btnInput.setText("Display Choices");
        
        btnClear.setText("Clear");
        
        btnInsert.setText("Insert");
        
        btnAlter.setText("Alter");
        
        btnRemove.setText("Remove");
        
        btnList.setText("List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
        		
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(radioFemale)
                                        .addGap(42, 42, 42)
                                        .addComponent(radioMale))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(checkMusic)
                                .addGap(18, 18, 18)
                                .addComponent(checkMovies)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkReading)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkSport)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInput)
                            .addComponent(btnClear))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnInsert)
                            .addGap(18, 18, 18)
                            .addComponent(btnAlter)
                            .addGap(18, 18, 18)
                            .addComponent(btnRemove)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioFemale)
                        .addComponent(radioMale)
                        .addComponent(jLabel5)
                        .addComponent(btnList))
                    .addGap(15, 15, 15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(checkMusic)
                        .addComponent(checkMovies)
                        .addComponent(checkReading)
                        .addComponent(checkSport))
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnInput)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    public ArrayList<JCheckBox> getHobby() {
		return hobby;
	}

	public JTextArea getExitArea() {
		return exitArea;
	}

	public JButton getBtnAlter() {
		return btnAlter;
	}

	public JButton getBtnInput() {
		return btnInput;
	}

	public JButton getBtnInsert() {
		return btnInsert;
	}

	public JButton getBtnClear() {
		return btnClear;
	}

	public JButton getBtnList() {
		return btnList;
	}

	public JButton getBtnRemove() {
		return btnRemove;
	}

	public ButtonGroup getBtnGender() {
		return btnGender;
	}

	public JCheckBox getCheckMovies() {
		return checkMovies;
	}

	public JCheckBox getCheckSport() {
		return checkSport;
	}

	public JCheckBox getCheckReading() {
		return checkReading;
	}

	public JCheckBox getCheckMusic() {
		return checkMusic;
	}

	public JComboBox getComboState() {
		return comboState;
	}

	public JLabel getjLabel1() {
		return jLabel1;
	}

	public JLabel getjLabel2() {
		return jLabel2;
	}

	public JLabel getjLabel3() {
		return jLabel3;
	}

	public JLabel getjLabel4() {
		return jLabel4;
	}

	public JLabel getjLabel5() {
		return jLabel5;
	}

	public JLabel getjLabel6() {
		return jLabel6;
	}

	public JLabel getjLabel7() {
		return jLabel7;
	}

	public JPanel getjPanel1() {
		return jPanel1;
	}

	public JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	public JRadioButton getRadioFemale() {
		return radioFemale;
	}

	public JRadioButton getRadioMale() {
		return radioMale;
	}

	public JTextField getTxtHeight() {
		return txtHeight;
	}

	public JTextField getTxtAge() {
		return txtAge;
	}

	public JTextField getTxtName() {
		return txtName;
	}

	public JTextField getTxtWeight() {
		return txtWeight;
	}

	/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextArea exitArea;
    private JButton btnAlter;
    private JButton btnInput;
    private JButton btnInsert;
    private JButton btnClear;
    private JButton btnList;
    private JButton btnRemove;
    private ButtonGroup btnGender;
    private JCheckBox checkMovies;
    private JCheckBox checkSport;
    private JCheckBox checkReading;
    private JCheckBox checkMusic;
    private JComboBox comboState;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JRadioButton radioFemale;
    private JRadioButton radioMale;
    private JTextField txtHeight;
    private JTextField txtAge;
    private JTextField txtName;
    private JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
